module.exports = {
    'likes': '{ likes, number } me gusta',
    'logout': 'Salir',
    'english': 'Inglés',
    'french': 'Français',
    'spanish': 'Español',
    'signup.subheading': 'Registrate y comparte fotos con tus amigos',
    'signup.facebook': 'Iniciar sesión con Facebook',
    'signup.text': 'Iniciar sesión',
    'email': 'Correo electronico',
    'username' : 'Nombre de usuario',
    'fullname' : 'Nombre completo',
    'password' : 'Contraseña',
    'signup.call-to-action': 'Regístrate',
    'signup.have-account': '¿Tienes una cuenta?',
    'signin': 'Entrar',
    'signin.not-have-account': '¿No tienes una cuenta?',
    'language' : 'Idioma',
    'upload-picture': 'Subir foto',
    'upload': 'Subir'
}